[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./mvnw package -DskipTests -B"]

[start]
cmd = "java -jar target/*.jar"

[variables]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
